<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>lidar_bringup</name>
  <version>0.1.0</version>
  <description>YDLIDAR X3 PRO 的启动包（参数 + launch，依赖 ydlidar_ros2_driver）</description>
  <maintainer email="kblueseek@users.noreply.github.com">kblue</maintainer>
  <license>MIT</license>
  <buildtool_depend>ament_python</buildtool_depend>
  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
